### ISSUE TITLE
Làm thế nào để đóng góp vào dự án vậy?

### ISSUE THREAD

**Issue by minhtanz1** [HoanChan/HC-MIX#1]
Mình muốn tìm hiểu cốt lõi của chương trình và mở rộng hơn nưa. Các tính năng cần thiết, nhưng mình không có tài liệu hoặc hướng dẫn để build từ github. Mong bạn hướng dẫn mình thanks!!!!

**Comment by HoanChan** [comment]
Hiện tại các file upload lên đây là các file dùng để cài đặt chứ không phải là mã nguồn của dự án. Dự án không có mở mã nguồn do đang sử dụng các công nghệ đã quá cũ, chạy ổn nhưng còn chậm lắm. Hiện mình đang tạm dừng dự án để nghiên cứu các công nghệ mới hơn để tái xây dựng lại dự án. Cảm ơn bạn đã quan tâm.
